//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printer_And_Ticket_Management_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Ticket
    {
        public int TicketID { get; set; }
        public string TicketDescription { get; set; }
        public Nullable<int> PrinterID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> OpenedBy { get; set; }
        public string States { get; set; }
        public string urgency { get; set; }
        public string ClosedBy { get; set; }
    
        public virtual Table_Branch Table_Branch { get; set; }
        public virtual Table_Printer Table_Printer { get; set; }
        public virtual Table_UserDetail Table_UserDetail { get; set; }
    }
}
