//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printer_And_Ticket_Management_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_AuditTrail
    {
        public int AuditTrailID { get; set; }
        public string Function_case { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
