//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printer_And_Ticket_Management_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Printer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Printer()
        {
            this.Table_PrinterAllocation = new HashSet<Table_PrinterAllocation>();
            this.Table_Ticket = new HashSet<Table_Ticket>();
        }
    
        public int PrinterID { get; set; }
        public string PrinterCode { get; set; }
        public string BrandName { get; set; }
        public Nullable<System.DateTime> PurchasedDate { get; set; }
        public string VendorName { get; set; }
        public string VendorContact { get; set; }
        public Nullable<int> WarrantyPeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_PrinterAllocation> Table_PrinterAllocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Ticket> Table_Ticket { get; set; }
    }
}
